# Generated by Django 4.2.3 on 2024-02-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishtories_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchdata',
            name='depth',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
